### ISSUE TITLE
Command + Q on Mac should behave like Chrome

### ISSUE THREAD

**Issue by axeleriksson147** [symphonyoss/SymphonyElectron#1000]
I always accidentally press Command + Q when I want to switch tabs closing Symphony. On Chrome a prompt shows up instead "Hold Command + Q to quit". If I press it again, it will close straight away. If I hold Command + Q it will also close the browser.

@sasha-symphony

**Comment by VishwasShashidhar** [comment]
Thank you @axeleriksson147, that makes sense. I'll bring this up with the PM.
