### ISSUE TITLE
Build instructions have stopped working (MacOSX)

### ISSUE THREAD

**Issue by pmonks** [symphonyoss/SymphonyElectron#137]
The build instructions in the [README](https://github.com/symphonyoss/SymphonyElectron/blob/master/README.md#build-instructions) worked just fine last time a tried it (a week or so ago), but seem to have stopped working recently.

**Steps to reproduce:**
1. Clone source locally
2. Switch to directory
3. Run: `npm install` (succeeds)
4. Run `npm run dist-mac`

**Expected result:**
DMG file is built.

**Actual result:**
```
$ npm run dist-mac
npm ERR! missing script: dist-mac

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pmonks/.npm/_logs/2017-06-09T21_54_26_796Z-debug.log
```
 
**Environmental information:**
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.5
BuildVersion:	16F73
$ uname -a
Darwin mthay.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
$ node --version
v8.1.0
```

**Comment by lneir** [comment]
sorry i need to update readme, we removed those steps.

if you want to test out locally, use: npm run dev

currently only supporting build msi (for windows via advanced installer) and pkg (for mac).  we'll update readme on how to build pkg.

**Comment by pmonks** [comment]
Cool - `pkg` packaging works too.  I can't really use the test locally version since I'm looking to build multiple different binaries with different pods configured (ODP and Foundation production pod).

**Comment by lneir** [comment]
i've updated the instructions to build pkg for mac.
