### ISSUE TITLE
Build is failing on macOS Sierra

### ISSUE THREAD

**Issue by pmonks** [symphonyoss/SymphonyElectron#153]
As of rev c4fb2ff, the build is failing on macOS Sierra with numerous copies of the Electron GUI app started, and all displaying the following dialog box:

![image](https://user-images.githubusercontent.com/54865/27882338-4990b37e-619a-11e7-9908-3e9bf98723ad.png)

**Environment**
macOS Sierra v10.12.5
npm v5.0.4
node.js v8.1.3

**Comment by lneir** [comment]
@VikasShashidhar can you help peter with issue above?  thanks.

**Comment by VikasShashidhar** [comment]
@lneir Sure. Looking into it.

**Comment by VikasShashidhar** [comment]
@pmonks We have a couple of open PRs that are being reviewed currently. As soon as we merge it, this issue will be resolved. This will most likely happen today or tomorrow.

Will keep you posted.

**Comment by VishwasShashidhar** [comment]
I was not able to reproduce this. 

1. Checked out the commit, created a build (.app), started it, it worked.
2. Created a .pkg from the .app and installed the app. Was able to get that to work as well.
3. Tried running the app directly as well with `npm run dev`, worked with that too.

@pmonks Can you let us know how to reproduce this / what steps you took?

**Comment by pmonks** [comment]
As of rev `717e17f` the build is working again.  Thanks!
