### ISSUE TITLE
Add Github project description

### ISSUE THREAD

**Issue by nyeates** [symphonyoss/SymphonyElectron#169]
There is a one-liner project descriptor that you can give Github repos. This helps when users are browsing various repos and want a one-liner to understand what it does and how it fits into the wider ecosytem. I noticed it missing when I was browsing all of symphonies repos. I am new to all of them. I wasn't sure what this repo was, amongst other popular symphony repos, and then had to click into it to read the readme (where, honestly, I still am unsure what this project does and how it fits in). This one-liner is your invitation card, or your elevator speech for new potential users/devs!

**Comment by VishwasShashidhar** [comment]
This has been taken care of. @nyeates Can you close this ticket please?
