### ISSUE TITLE
Certificate error on startup

### ISSUE THREAD

**Issue by pmonks** [symphonyoss/SymphonyElectron#209]
As of rev 89e8238 the following certificate error pops up after logging in:

![image](https://user-images.githubusercontent.com/54865/31343770-6fae2fca-acc5-11e7-8254-6622ecda83e9.png)

Clicking "Allow" seems to get past this issue without any negative side-effects, but it's a bit disconcerting to get this error each time the app starts.

**Comment by lneir** [comment]
@pmonks that warning is happening because some apps (in this case newapps) backend is not working.  for now you can safely ignore, we in process of removing this warning dialog and adding some internal logging.

@VikasShashidhar isn't this warning removed in newer builds?

**Comment by lneir** [comment]
sorry ignore my last msg.
@VikasShashidhar please investigate.
likely need to open ticket for team that opens newsapp.
@pmonks thanks for reporting, you can ignore for now.

**Comment by lneir** [comment]
so it appears the cert if not valid... here is screenshot... 
<img width="1395" alt="screen shot 2017-10-09 at 8 54 05 am" src="https://user-images.githubusercontent.com/1760440/31346949-a01da456-accf-11e7-9ff2-a1529509321a.png">

**Comment by lneir** [comment]
i reported issue and is being investigated by engineering services team.

**Comment by pmonks** [comment]
Cool thanks @lneir!

**Comment by pmonks** [comment]
Yep all fixed, and I didn't rebuild either.  I guess this was a server-side issues?
