### ISSUE TITLE
How does notifications work on MacOS?

### ISSUE THREAD

**Issue by bluechips23** [symphonyoss/SymphonyElectron#212]
I got SymphonyElectron working on my MacOS (10.12.6). I got the client running with "npm run dev". It works great but one major concern - how does notifications work? How do I enable them such that I can receive notifications on top corner of my screen? Or is it not supported on Mac client?

**Comment by lneir** [comment]
there is a demo app where you can see notifications: npm run demo-mac

**Comment by bluechips23** [comment]
The notifications on demo-mac look great. Is there a way I can enable them when I am launching the app with "npm run dev" or with "npm run packed-mac"?

**Comment by bluechips23** [comment]
Closing this since the newest version of Symphony supports notifications on Mac.
