### ISSUE TITLE
Exception on startup rev 488c478

### ISSUE THREAD

**Issue by pmonks** [symphonyoss/SymphonyElectron#236]
Rev 488c478 fails to start with the following exception:

![image](https://user-images.githubusercontent.com/54865/32741461-2882b9b6-c85b-11e7-8093-2a39507577a6.png)

**Comment by VishwasShashidhar** [comment]
@pmonks Please run `npm install` and try again, one of the dependencies is not installed.

**Comment by pmonks** [comment]
That did it!
