### ISSUE TITLE
NOTICE file non-compliant

### ISSUE THREAD

**Issue by copiesofcopies** [symphonyoss/SymphonyElectron#29]
The NOTICE file doesn't conform to the Foundation's [contribution policy](https://symphonyoss.atlassian.net/wiki/display/FM/Legal+Requirements). It should be in this form:

```Symphony Electron - Symphony Software Foundation
Copyright [XXXX-XXXX] [Copyright holder 1 - name and email]
Copyright [XXXX-XXXX] [Copyright holder 2 - name and email]
...
Copyright [XXXX-XXXX] [Copyright holder N - name and email]
 
This product includes software developed at the Symphony Software Foundation (http://symphony.foundation).
```
It should include copyright notices for every contributor. In this case, perhaps that's only Symphony LLC?

**Comment by VikasShashidhar** [comment]
@lneir Isn't this something we should receive from the legal team?

**Comment by lneir** [comment]
@VikasShashidhar  this is open sourced through the symphony foundation, so we should be following their procedure.
