### ISSUE TITLE
Missing Search Library?

### ISSUE THREAD

**Issue by macserv** [symphonyoss/SymphonyElectron#367]
I've managed to build the Symphony Electron client successfully on macOS (for the most part), but it's crashing on launch due to a missing dynamic library: `libsymphonysearch.dylib`.  Indeed, `package.json` would suggest that this library should be included with the build, but it's missing from the `/library` folder of the project.

The documentation and my Google-fu are failing me... Is there another project (or projects) that I need to build first, in order to first obtain that library?  Apologies if I'm missing something obvious.

**Comment by macserv** [comment]
@VishwasShashidhar Might you be able to offer a suggestion here?

**Comment by VishwasShashidhar** [comment]
@macserv Thanks for informing. I think we need to update the documentation. We've not included the library as part of the repo.

If you have access to filevault / jenkins, I can share an appropriate link.

**Comment by macserv** [comment]
Thanks for the reply!  I'm not sure if I have access or not... which means I probably don't.  How do I validate / request access?

**Comment by VishwasShashidhar** [comment]
@serkanmulayim Can you help with the above please?

**Comment by keerthi16** [comment]
@macserv Please check out the latest master we longer need those libraries to build. 
Closing this ticket. 
@macserv Please reopen this if you face any problems with this. Thanks.
