### ISSUE TITLE
installer/win/Symphony.exe infected with a virus

### ISSUE THREAD

**Issue by SkyLeach** [symphonyoss/SymphonyElectron#371]
![screen shot 2018-05-20 at 11 47 42 am](https://user-images.githubusercontent.com/940228/40280575-a5dea72e-5c23-11e8-9bfe-e9e98936c46e.png)

**Comment by SkyLeach** [comment]
I got that after my initial clone of the repo.  No build.

```
|💀> git log -n1
commit 8037d16000e957c034b5ffab2cc0ed36c54d6285 (HEAD -> master, origin/master, origin/HEAD)
Author: Kiran Niranjan <kiran@kike.co.in>
Date:   Fri May 18 09:55:19 2018 +0530

    ELECTRON-464 - Update title bar with new logo (#370)

```

**Comment by VishwasShashidhar** [comment]
@SkyLeach You are right. There was a stale file hanging around. I've removed it. The latest clone shouldn't have the file now.
