### ISSUE TITLE
Broader gitignore support

### ISSUE THREAD

**Issue by VishwasShashidhar** [symphonyoss/SymphonyElectron#43]
We should add a broader support for gitignore to ignore files generated by the following components

Node, VisualStudio, Eclipse, Jetbrains, Linux, Netbeans, SublimeText, TextMate, Vim, Windows, macOS, VisualStudioCode.

The updated file will be as attached.
[gitignore-updated.txt](https://github.com/symphonyoss/SymphonyElectron/files/869695/gitignore-updated.txt)

**Comment by ivishwas-s** [comment]
I have a branch ready with this change, however, I don't have access to push it to the repo. I want to push the branch and create a PR. Can anyone help?

**Comment by lneir** [comment]
we use fork and pull model here.

**Comment by ivishwas-s** [comment]
Done. Please review and merge.
