### ISSUE TITLE
Packaged dist incorrectly detecting network state

### ISSUE THREAD

**Issue by joercampbell** [symphonyoss/SymphonyElectron#705]
**Describe the bug**
Cloned the most recent repository (1.55.3 version) and compiled and ran it as dev. This all worked quite well after I modified the configuration to point to a company SSO instance of the Symphony services. I then ran unpackaged-mac to create a distro of the executable - it also seemed to build - but in running that distro standalone I am getting an error after it shows me the splash screen indicating an SSO login to my corp instance of Symphony. I imagine as a result reproduction is going to involve me directly helping someone because the steps to reproduce are likely specific to the networking environment that I am involved in.

**Expected behavior**
I expected that the dist version would run exactly like the dev local version of the build did. The dev running in a shell works perfectly - the dist version of the same config fails.

**Screenshots**
1 and 2 are from an npm run dev on the command line. #3 is what occurs in the dist version of the application.

**Desktop (please complete the following information):**
 - OS: MacOS Mojave (10.14.5)
 - App Version 1.55.3

**Comment by joercampbell** [comment]
![1](https://user-images.githubusercontent.com/1405374/60818706-30df6f00-a16c-11e9-88ad-eeb66a9cb634.png)
![2](https://user-images.githubusercontent.com/1405374/60818707-30df6f00-a16c-11e9-9fbd-d230619d807d.png)
<img width="902" alt="3" src="https://user-images.githubusercontent.com/1405374/60818708-30df6f00-a16c-11e9-9403-edbe8794d6a3.png">

**Comment by VishwasShashidhar** [comment]
@joercampbell Thank you for opening an issue with the detailed description.

`unpacked-mac` basically has a configuration file called `Symphony.config` that essentially creates a default value for the pod url with the value `https://foundation-dev.symphony.com`.

There are 3 ways you can resolve this issue:

1. Use `packed-mac` to create a .pkg file which allows you to configured the POD you desire to point to. Note: This requires you installing the app `http://s.sudre.free.fr/Software/Packages/about.html`

2. Right click on `Symphony.app` and use `Show Package Contents`, navigate to `Contents/config`, open `Symphony.config` and change the value for the property `url` to the desired POD url you'd like to point to.

3. Before you run `unpacked-mac`, change the value of the `url` property in `Symphony.config` file under the `config` directory in your project root to the desired POD url you'd like to point to.

**Comment by joercampbell** [comment]
Yup - Totally got all that.

I have actually tried all three of those things already and still no joy.
In the 2nd and 3rd cases - it comes up with the right SSO looking page but
then goes to the network error when clicking. In the 1st case, the same is
true after I change the url in the setup to point to the right place for my
login.

None of these kept the app from erroring when BUILT as a distro or as a
package for install.

Thanks,
    Joe

**Comment by VishwasShashidhar** [comment]
@joercampbell Which branch are you building against? And, can you share the SSO url you are trying to connect to please? Also, a HAR file would be useful so we can understand what's going on.

**Comment by joercampbell** [comment]
Building against master.

Barclays.symphony.com

And what is a Har file? Happy to generate anything needed to help debug.

Joe

**Comment by VishwasShashidhar** [comment]
@joercampbell Please use dev tools and capture the network trace, that'll generate a HAR file. Below screenshot will help.

<img width="1286" alt="Screenshot 2019-07-09 at 16 57 49" src="https://user-images.githubusercontent.com/5968790/60884534-b6e1df80-a26a-11e9-9486-b086e3041c58.png">

**Comment by VishwasShashidhar** [comment]
@joercampbell I found the problem. It's probably because of a self-signed certificate. In the `Symphony.config` file, please set the parameter **ctWhitelist** to `"ctWhitelist": ["barclayscorp.com"]`. That should resolve your issue. This doesn't happen on dev environment because we basically override certificate errors.

**Comment by VishwasShashidhar** [comment]
If that resolves your issue and you have no other questions, please feel free to close the ticket. I'll wait till tomorrow to close this unless you have something else. Thanks!

**Comment by joercampbell** [comment]
Yes - that did resolve the issue. A touch more documentation around that as a param would be SUPER dandy... if there is a place I can attempt to build that documentation for you please let me know as I would be happy to issue a pull request around how that param works.

Thanks!

**Comment by VishwasShashidhar** [comment]
Thanks @joercampbell, we have all this documented in our internal Confluence. I'll be pushing some of them to this repo as well. Appreciate your support though 👍
